"""Game-based curriculum covering Python's core language and standard-library skills."""

CURRICULUM = [
    ("01", "Running Python", ["interpreter", "expressions", "print"]),
    ("02", "Variables and names", ["assignment", "identifiers", "constants"]),
    ("03", "Numbers and operators", ["int", "float", "complex", "arithmetic", "bitwise"]),
    ("04", "Strings", ["indexing", "slicing", "formatting", "encoding"]),
    ("05", "Lists, tuples, sets and dictionaries", ["collections", "comprehensions"]),
    ("06", "Control flow", ["if", "for", "while", "match", "break", "continue"]),
    ("07", "Functions", ["def", "parameters", "scope", "lambda", "annotations"]),
    ("08", "Errors and exceptions", ["try", "except", "else", "finally", "raise"]),
    ("09", "Modules and packages", ["import", "packages", "__name__"]),
    ("10", "Files and paths", ["open", "pathlib", "serialization"]),
    ("11", "Classes and objects", ["class", "methods", "inheritance", "composition"]),
    ("12", "Dataclasses, enums and protocols", ["dataclass", "Enum", "Protocol"]),
    ("13", "Iterators and generators", ["iter", "next", "yield", "generator expressions"]),
    ("14", "Decorators and context managers", ["decorator", "with", "__enter__", "__exit__"]),
    ("15", "Typing and generics", ["typing", "Generic", "TypeVar", "Union", "Literal"]),
    ("16", "Pattern matching", ["match", "case", "guards"]),
    ("17", "Async programming", ["async", "await", "asyncio"]),
    ("18", "Threads and processes", ["threading", "concurrency", "multiprocessing concepts"]),
    ("19", "Testing and debugging", ["assert", "unittest", "logging", "tracebacks"]),
    ("20", "Standard library", ["json", "sqlite3", "datetime", "math", "random", "itertools", "functools"]),
    ("21", "Networking", ["sockets", "HTTP concepts", "client/server"]),
    ("22", "Python data model", ["dunder methods", "protocols", "attribute access"]),
    ("23", "Metaprogramming", ["descriptors", "metaclasses", "class creation"]),
    ("24", "Packaging and environments", ["venv", "pip", "pyproject.toml"]),
    ("25", "Capstone: build your own pet", ["architecture", "testing", "packaging"]),
]
