plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.odelly.epilepsysafety'
    compileSdk 35
    defaultConfig {
        applicationId 'com.odelly.epilepsysafety'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '0.3.0-beta'
    }
    testOptions { unitTests.returnDefaultValues = true }
}

chaquopy {
    defaultConfig {
        version = '3.13'
    }
}

dependencies { testImplementation 'junit:junit:4.13.2' }
